/*
Created By   :- Premanath Reddy
Pupose       :- This static class is using in Opp_Activity_history Trigger and UpdateCurrency Trigger.
                if(staticFlag.Opp_Activity_hist){
                    staticFlag.Opp_Activity_hist = false;
                }
*/

public class staticFlag {

    public static boolean Opp_Activity_hist= true;
    public static boolean Update_Currency=true;
    
}